const data = {
    products:[
        {
            _id:1,
            name:"test 1",
            category:"test",
            image:"/images/p1.jpg",
            price:120,
            brand:"test",
            rating:4.5,
            numReviews:10,
            decription:"kappa",
        },
        {
            _id:2,
            name:"test 2",
            category:"test",
            image:"/images/p2.jpg",
            price:120,
            brand:"test",
            rating:4.5,
            numReviews:10,
            decription:"kappa",
        },
        {
            _id:3,
            name:"test 3",
            category:"test",
            image:"/images/p3.jpg",
            price:120,
            brand:"test",
            rating:4.5,
            numReviews:10,
            decription:"kappa",
        },
        {
            _id:4,
            name:"test 4",
            category:"test",
            image:"/images/p4.jpg",
            price:120,
            brand:"test",
            rating:4.5,
            numReviews:10,
            decription:"kappa",
        },
        {
            _id:5,
            name:"test 5",
            category:"test",
            image:"/images/p5.jpg",
            price:120,
            brand:"test",
            rating:5,
            numReviews:10,
            decription:"kappa",
        },
        {
            _id:6,
            name:"test 6",
            category:"test",
            image:"/images/p6.jpg",
            price:120,
            brand:"test",
            rating:4,
            numReviews:10,
            decription:"kappa",
        },
    ]
}

export default data;